spring:
  profiles:
    active: test
---
spring:
  profiles: test
  application:
    name: spring_cloud_test
server:
  port: 8080
---
spring:
  profiles: prod
  application:
    name: spring_cloud_prod
server:
  port: 8081