spring:
  profiles:
    active: dev
---
spring:
  profiles: test
  application:
    name: myConfigClient-test
server:
  port: 8080
---
spring:
  profiles: dev
  application:
    name: myConfigClient-dev
server:
  port: 8081
management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: "*"
sign: N   