sign: Y
management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: "*"
spring:
  profiles:
    active: dev
---
spring:
  profiles: test
  application:
    name: myMqConfigClient-test
server:
  port: 8080
---
spring:
  profiles: dev
  application:
    name: myMqConfigClient-dev
server:
  port: 8081 